import 'package:flutter/material.dart';

final ColorScheme appColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Colors.orange,
  onPrimary: Colors.white,
  primaryContainer: Colors.orange.shade200,
  onPrimaryContainer: const Color(0xFFFFFFFF),
  secondary: Colors.orange.shade100,
  onSecondary: const Color(0xFF000000),
  secondaryContainer: Colors.orange.shade50,
  onSecondaryContainer: const Color(0xFF000000),
  tertiary: const Color(0xFF26A69A),
  onTertiary: const Color(0xFFFFFFFF),
  tertiaryContainer: const Color(0xFF80CBC4),
  onTertiaryContainer: const Color(0xFF000000),
  error: const Color(0xFFB00020),
  onError: const Color(0xFFFFFFFF),
  errorContainer: const Color(0xFFFF7F7F),
  onErrorContainer: const Color(0xFF000000),
  surface: Colors.white,
  onSurface: const Color(0xFF000000),
  onSurfaceVariant: const Color(0xFF000000),
  outline: Colors.black38,
  outlineVariant: Colors.orange.shade400,
  shadow: const Color(0xFF000000),
  scrim: const Color(0xFF000000),
  inverseSurface: const Color(0xFF000000),
  onInverseSurface: const Color(0xFFFFFFFF),
  inversePrimary: Colors.white,
  surfaceTint: Colors.orange.shade700,

  // For greyed out things
  primaryFixedDim: Colors.grey,
  onPrimaryFixedVariant: Colors.white,
);

final ColorScheme appDarkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Colors.orange.shade200,
  onPrimary: Colors.black,
  primaryContainer: Colors.orange.withAlpha(50),
  onPrimaryContainer: const Color(0xFFFFFFFF),
  secondary: Colors.orange.shade100,
  onSecondary: const Color(0xFF000000),
  secondaryContainer: Colors.orange.withAlpha(100),
  onSecondaryContainer: const Color(0xFF000000),
  tertiary: const Color(0xFF26A69A),
  onTertiary: const Color(0xFFFFFFFF),
  tertiaryContainer: const Color(0xFF4DB6AC),
  onTertiaryContainer: const Color(0xFF000000),
  error: const Color(0xFFCF6679),
  onError: const Color(0xFF000000),
  errorContainer: const Color(0xFFB00020),
  onErrorContainer: const Color(0xFFFFFFFF),
  surface: const Color(0xFF1E1E1E),
  onSurface: const Color(0xFFFFFFFF),
  onSurfaceVariant: const Color(0xFFB0BEC5),
  outline: Colors.white38,
  outlineVariant: Colors.orange.shade400,
  shadow: const Color(0xFF000000),
  scrim: const Color(0xFF000000),
  inverseSurface: Colors.orange.shade50,
  onInverseSurface: const Color(0xFF000000),
  inversePrimary: Colors.black,
  surfaceTint: Colors.orange.shade700,

  // For greyed out things
  primaryFixedDim: Colors.grey,
  onPrimaryFixedVariant: Colors.black,
);
