// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgq55GHiufHlaagf6HCyWo_ucM5L_c5Yo',
    appId: '1:836496669919:web:e3ed923bbc4cc3afd53d6a',
    messagingSenderId: '836496669919',
    projectId: 'bandits-bytetracker',
    authDomain: 'bandits-bytetracker.firebaseapp.com',
    storageBucket: 'bandits-bytetracker.firebasestorage.app',
    measurementId: 'G-B42G1JQSDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgwyf5RzAPGzao38-onvfYYxpXWGEN9Q',
    appId: '1:836496669919:android:f308d8044cc58cd1d53d6a',
    messagingSenderId: '836496669919',
    projectId: 'bandits-bytetracker',
    storageBucket: 'bandits-bytetracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAXSucNyreJtZVU-KyhSRl8n1ZyUlx17g',
    appId: '1:836496669919:ios:57622488d232f7bcd53d6a',
    messagingSenderId: '836496669919',
    projectId: 'bandits-bytetracker',
    storageBucket: 'bandits-bytetracker.firebasestorage.app',
    iosBundleId: 'com.example.byteTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAXSucNyreJtZVU-KyhSRl8n1ZyUlx17g',
    appId: '1:836496669919:ios:57622488d232f7bcd53d6a',
    messagingSenderId: '836496669919',
    projectId: 'bandits-bytetracker',
    storageBucket: 'bandits-bytetracker.firebasestorage.app',
    iosBundleId: 'com.example.byteTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgq55GHiufHlaagf6HCyWo_ucM5L_c5Yo',
    appId: '1:836496669919:web:dd2e782aa2f4c5f0d53d6a',
    messagingSenderId: '836496669919',
    projectId: 'bandits-bytetracker',
    authDomain: 'bandits-bytetracker.firebaseapp.com',
    storageBucket: 'bandits-bytetracker.firebasestorage.app',
    measurementId: 'G-DT8NJQY3S1',
  );
}
